bankroll:
  starting: 4000
  kelly_fraction: 0.25
  max_bet_fraction_of_roll: 0.025
risk:
  daily_stop_loss_pct: 0.06
  daily_max_staked_pct: 0.12
bayesian_update:
  priors:
    default:
      mu: 0.55
      n: 45
    HR:
      mu: 0.11
      n: 40
    Hits:
      mu: 0.63
      n: 60
    Bases:
      mu: 0.2
      n: 40
  bias_correction:
    Demon-Moon:
      boost: 0.04
      half_life_days: 21
    Goblin:
      boost: 0.02
      half_life_days: 21
diversification:
  max_same_player_per_slip: 1
  demon_quota_per_slip: 1
  demon_quota_per_day: 6
sizing:
  kelly_fraction_override:
    Demon: 0.1
    Goblin: 0.15
filters:
  min_edge: 0.03
  min_expected_value: 1.05
payouts:
  Power4: 10.0
  Power6: 37.5
  Flex6:
    six_correct: 25.0
    five_correct: 2.0
    four_correct: 0.4
logging:
  version_tag: v6.8
  auto_backtest_days: 30
data:
  weather_provider: open_meteo
  weather_cache: data/cache/
model_assets:
  hit_prob_v1: model_assets/model_v1.pkl
min_edge_pp: 0.05
