[pytest]
filterwarnings =
    ignore:`use_label_encoder` is deprecated:UserWarning
    ignore:is_sparse is deprecated:DeprecationWarning
    ignore:is_categorical_dtype is deprecated:DeprecationWarning
    ignore:product is deprecated:DeprecationWarning
