name: PP-EDGE CI

on:
  push:
    branches: ["**"]          # build every branch
  pull_request:
    branches: ["main"]        # and every PR into main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependenciesn        run: |n          python -m pip install --upgrade pipn          pip install -r requirements.txt      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: pytest -q
