name: lint_workflows_push
on:
  push:
    paths:
      - .github/workflows/*.yml
      - .github/workflows/*.yaml

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          actionlint_flags: "-color"
